Use drain script to signal TERM to service-backup process
This allows arbitrary time for the child processes to clean up and terminate
This is not possible in the control script, which is time-limited.

Also increase time limit in monit stop to 180 seconds

[finishes #153425822]

Signed-off-by: Kieron Browne <kbrowne@pivotal.io>

diff --git a/jobs/service-backup/templates/ctl.erb b/jobs/service-backup/templates/ctl.erb
--- a/jobs/service-backup/templates/ctl.erb
+++ b/jobs/service-backup/templates/ctl.erb
@@ -1,4 +1,4 @@
-#!/bin/bash -e
+#!/bin/bash
 
 # Copyright (C) 2016-Present Pivotal Software, Inc. All rights reserved.
 # This program and the accompanying materials are made available under the terms of the under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License.
@@ -7,7 +7,7 @@
 # Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
 
 
-set -o pipefail
+set -eo pipefail
 
 mkdir -p /var/vcap/sys/log/monit
 
@@ -46,6 +46,7 @@ case $1 in
     backup_conf=/var/vcap/jobs/service-backup/config/backup.yml
 
     export GCP_SERVICE_ACCOUNT_FILE=/var/vcap/jobs/service-backup/config/gcp_service_account.json
+    set +e
     start-stop-daemon \
       --start \
       --pidfile $pidfile \
@@ -54,6 +55,7 @@ case $1 in
       --chuid "${backup_user}:${backup_user}" \
       --startas /bin/bash \
       -- -c "exec $backup_daemon $backup_conf &>> $backup_log_file"
+    set -e
 
     log "start script: completed starting service-backup"
     ;;
@@ -61,29 +63,29 @@ case $1 in
   stop)
     log "stop script: stopping service-backup"
 
+    set +e
     start-stop-daemon \
       --stop \
-      --pidfile $pidfile \
-      --retry "TERM/15/QUIT/15/KILL/15" \
-      --oknodo
+      --signal KILL \
+      --pidfile $pidfile
 
-      exit_status=$?
-      set -e
+    exit_status=$?
+    set -e
 
-      case "${exit_status}" in
-	0)
-	  log "stop script: completed stopping service-backup"
-	  rm ${pidfile}
-	  ;;
-	2)
-	  log "stop script: failed to shutdown in 45 seconds"
-	  exit 1
-	  ;;
-	*)
-	  log "stop script: failed to exit. Start-stop-daemon exit_status: ${exit_status}"
-	  exit 1
-	  ;;
-      esac
+    case "${exit_status}" in
+      0)
+	log "stop script: completed stopping service-backup"
+	rm ${pidfile}
+	;;
+      1)
+	log "stop script: service-backup was not running"
+	rm ${pidfile}
+	;;
+      *)
+	log "stop script: failed to exit. Start-stop-daemon exit_status: ${exit_status}"
+	exit 1
+	;;
+    esac
     ;;
 
   *)
